    - name: Setup Android NDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: '25.2.9519653'

    - name: Download and Build Hev-Socks5-Tunnel
      run: |
        curl -L -o hev.tar.xz https://github.com/unarto/hev-socks5-tunnel/releases/download/2.15.0/hev-socks5-tunnel-2.15.0.tar.xz
        tar -xf hev.tar.xz
        cd hev-socks5-tunnel-2.15.0
        
        mkdir -p ../app/src/main/jniLibs/arm64-v8a
        mkdir -p ../app/src/main/jniLibs/armeabi-v7a
        
        make ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT ARCH=arm64
        cp bin/hev-socks5-tunnel ../app/src/main/jniLibs/arm64-v8a/libhev-socks5-tunnel.so
        make clean
        
        make ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT ARCH=arm
        cp bin/hev-socks5-tunnel ../app/src/main/jniLibs/armeabi-v7a/libhev-socks5-tunnel.so
